const actionType = {
    SPIN_PIG: 'SPIN_PIG',
    INIT_PIG: 'INIT_PIG',
    SET_VISIBLE_PIG: 'SET_VISIBLE_PIG',
    SET_ADD_AGE: 'SET_ADD_AGE',
    ADD_PIG_BEFORE: 'ADD_PIG_BEFORE',
    ADD_PIG_AFTER: 'ADD_PIG_AFTER',
    SET_PIG_KIND: 'SET_PIG_KIND',
    SET_KIND_OF_ADD: 'SET_KIND_OF_ADD',
    SET_GENDER_OF_ADD: 'SET_GENDER_OF_ADD',
    SHOW_MODIFY_MODAL: 'SHOW_MODIFY_MODAL',
    SET_VISIBLE_OF_MODAL: 'SET_VISIBLE_OF_MODAL',
    SET_AGE_OF_MODIFY: 'SET_AGE_OF_MODIFY',
    MODIFY_PIG_BEFORE: 'MODIFY_PIG_BEFORE',
    MODIFY_PIG_AFTER: 'MODIFY_PIG_AFTER',
    SET_ID_OF_SEARCH_PIG: 'SET_ID_OF_SEARCH_PIG',
    SEARCH_PIG: 'SEARCH_PIG'

}

export default actionType;
