const actionType = {
    SPIN: 'SPIN',
    INIT: 'INIT',
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_VISIBLE: 'SET_VISIBLE',
    SET_MODAL_ACCOUNT: 'SET_MODAL_ACCOUNT',
    SET_PWD: 'SET_PWD',
    SET_RE_PWD: 'SET_RE_PWD',
    ADD_CHECK: 'ADD_CHECK',
    ADD: 'ADD',
    ACCOUNT_TIP_CHECK: 'ACCOUNT_TIP_CHECK',
    SET_USERNAME: 'SET_USERNAME',
    ADD_BEFORE: 'ADD_BEFORE',
    ADD_AFTER: 'ADD_AFTER',
    SET_VISIBLE_1: 'SET_VISIBLE_1',
    SET_USERNAME_1: 'SET_USERNAME_1',
    MODIFY_BEFORE: 'MODIFY_BEFORE',
    MODIFY_AFTER: 'MODIFY_AFTER'
}

export default actionType;
